---
name: Práctica Listas
locale: es
type: practice
beta: false
language: haskell
id_format: "%05d"
order:
- 21
- 38
- 23
- 31
- 22
- 24
- 32
- 33
- 34
- 35
- 36
- 39
- 311
- 312
- 313
- 317
- 318
- 321
- 319
- 320
- 322
private: false
