---
locale: es
tags: []
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: Ejercicio diseñado por Alfredo Sanzo en 2014.
manual_evaluation: false
choices: []
name: Cuántas Muzzas
